sudo: required
language: generic

services:
  - docker

before_install: 
  - docker build -t devji79/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true devji79/docker-react-app npm run test

